name: Sync & Publish Versions

on:
  push:
    branches: [main]
    paths-ignore:
    - '.devcontainer/**'
    - '.vscode/**'
    - 'tests/**'
    - '.*'
    - '*.js'
    - '*.json'
    - '*.lock'
    - '*.md'
    - '*.neon'
    - '*.xml'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  css-lint:
    uses: ./.github/workflows/css-lint.yml

  javascript-code-quality:
    uses: ./.github/workflows/javascript-code-quality.yml

  php-code-quality:
    uses: ./.github/workflows/php-code-quality.yml

  shell-code-quality:
    uses: ./.github/workflows/shell-code-quality.yml

  validate-sql:
    needs: [css-lint, javascript-code-quality, php-code-quality, shell-code-quality]
    uses: ./.github/workflows/validate-sql.yml

  publish-version:
    needs: [validate-sql]
    uses: ./.github/workflows/publish-version-json.yml
    permissions:
      contents: write
